### ISSUE TITLE
Error when using Expression as ritual condition

### ISSUE THREAD

**Issue by bunnies1230** [xIdentified/Devotions#12]
I was configuring my rituals to require a certain threshold of favor to use, utilizing a placeholder expression, but any time the expression is enabled, whether it's true or false, it throws an error and nothing happens. Removing the expression causes the ritual to function normally. Is the placeholder a string maybe?

### rituals.yml
>   devotion_ritual:
    display_name: "Ritual of Devotion"
    description: "When your devotion wanes, your god offers a path back. \nRequirements | under 150 Favor"
    favor: 20
    item: "VANILLA:BOOK"
     conditions:
        expression: "%devotions_favor% < 150"
    objectives:
      - type: "MEDITATION"
        description: "Stand still and meditate at the shrine for 60 seconds"
        target: PLAYER
        count: 60
    outcome-command: 
      - "effect give @p minecraft:absorption 600 1 true"

### console error
> [10:42:05] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Devotions v1.2.8-beta
java.lang.NoClassDefFoundError: Could not initialize class me.xidentified.devotions.util.JavaScriptEngine
	at me.xidentified.devotions.rituals.Ritual.validateConditions(Ritual.java:56) ~[Devotions-1.2.8-beta.jar:?]
	at me.xidentified.devotions.managers.RitualManager.startRitual(RitualManager.java:85) ~[Devotions-1.2.8-beta.jar:?]
	at me.xidentified.devotions.listeners.ShrineListener.handleRitualInteraction(ShrineListener.java:118) ~[Devotions-1.2.8-beta.jar:?]
	at me.xidentified.devotions.listeners.ShrineListener.onShrineInteract(ShrineListener.java:85) ~[Devotions-1.2.8-beta.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor366.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-436]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-436]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-436]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593) ~[paper-1.20.4.jar:git-Paper-436]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1935) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-436]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1455) ~[paper-1.20.4.jar:git-Paper-436]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-436]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1432) ~[paper-1.20.4.jar:git-Paper-436]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[paper-1.20.4.jar:git-Paper-436]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1547) ~[paper-1.20.4.jar:git-Paper-436]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[paper-1.20.4.jar:git-Paper-436]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-436]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by xIdentified** [comment]
Fixed by switching to Rhino [here](https://github.com/xIdentified/Devotions/commit/c45eaeea82c138f4987ad63dc747d51cf1ebadf8). :smile:
