### ISSUE TITLE
Offering a placeable item on side of shrine does not consume item

### ISSUE THREAD

**Issue by bunnies1230** [xIdentified/Devotions#7]
Configured a block (bedrock, hay bale) as an offer-able item and when I placed it on the side of the shrine block, it gets placed in the world _and_ is counted as an offering. Later, it instead throws an error entirely, placing the block, fails to count as an offering, and throws this error message:

> [18:18:40] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Devotions v1.2.4-beta
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:567) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:503) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1580) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:33) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1191) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1170) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1163) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.util.thread.IAsyncTaskHandler.bu(SourceFile:115) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1146) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1060) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4024-Spigot-c198da2-1617847]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.HashMap org.bukkit.inventory.PlayerInventory.removeItemAnySlot(org.bukkit.inventory.ItemStack[])'
	at me.xidentified.devotions.listeners.ShrineListener.takeItemInHand(ShrineListener.java:178) ~[?:?]
	at me.xidentified.devotions.listeners.ShrineListener.handleOfferingInteraction(ShrineListener.java:141) ~[?:?]
	at me.xidentified.devotions.listeners.ShrineListener.onShrineInteract(ShrineListener.java:110) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor136.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 22 more

**Comment by xIdentified** [comment]
Thanks for letting me know, changed the method I was using to take the item out of the player's hand to work better on Spigot and Bukkit servers. Also added a check to make sure blocks aren't placed.
